### ISSUE TITLE
Error Selenium docker

### ISSUE THREAD

**Issue by Royalxm** [vyahello/badoo-liker#9]
Hey i have this error :

badoo-infinite-scheduler | [2021-06-13 19:54:05 INFO] Operating 50 badoo like attempts, in progress ...
badoo-infinite-scheduler | Traceback (most recent call last):
badoo-infinite-scheduler |   File "liker.py", line 46, in <module>
badoo-infinite-scheduler |     _run_badoo_liker()
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
badoo-infinite-scheduler |     return self.main(*args, **kwargs)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
badoo-infinite-scheduler |     rv = self.invoke(ctx)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
badoo-infinite-scheduler |     return ctx.invoke(self.callback, **ctx.params)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
badoo-infinite-scheduler |     return callback(*args, **kwargs)
badoo-infinite-scheduler |   File "liker.py", line 42, in _run_badoo_liker
badoo-infinite-scheduler |     executor.run()
badoo-infinite-scheduler |   File "liker.py", line 29, in run
badoo-infinite-scheduler |     self._liker.start(self._attempts, self._message_to_send)
badoo-infinite-scheduler |   File "/code/badoo/services.py", line 33, in start
badoo-infinite-scheduler |     self._badoo_page.like()
badoo-infinite-scheduler |   File "/code/badoo/web/workflow.py", line 80, in like
badoo-infinite-scheduler |     "profile-action--color-yes"
badoo-infinite-scheduler |   File "/code/badoo/web/support/element.py", line 134, in click
badoo-infinite-scheduler |     self.wait_to_be_clickable()._element().click()
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
badoo-infinite-scheduler |     self._execute(Command.CLICK_ELEMENT)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
badoo-infinite-scheduler |     return self._parent.execute(command, params)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
badoo-infinite-scheduler |     self.error_handler.check_response(response)
badoo-infinite-scheduler |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
badoo-infinite-scheduler |     raise exception_class(message, screen, stacktrace)
badoo-infinite-scheduler | selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element `<div class="profile-action profile-action--lg profile-action--color-yes profile-action--filled   js-profile-header-vote-yes js-profile-header-vote" data-choice="yes" role="button">...</div> is not clickable at point (292, 796). Other element would receive the click: <aside class="ovl js-ovl-close">...</aside>`

**Comment by Royalxm** [comment]
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="profile-action profile-action--lg profile-action--color-yes profile-action--filled   js-profile-header-vote-yes js-profile-header-vote" data-choice="yes" role="button">...</div> is not clickable at point (292, 796). Other element would receive the click: <aside class="ovl js-ovl-close">...</aside>

**Comment by Royalxm** [comment]
Ok my dab dont run badoo same time...
